const db = require('./db');

const GLOBAL_DICTIONARY = [
    // --- GENERAL / COMMON ---
    { turkish: "merhaba", ottoman: "مرحبا", category: "GENERAL" },
    { turkish: "selam", ottoman: "سلام", category: "GENERAL" },
    { turkish: "nasılsın", ottoman: "ناصلسڭ", category: "GENERAL" },
    { turkish: "teşekkür", ottoman: "تشكر", category: "GENERAL" },
    { turkish: "evet", ottoman: "اوت", category: "GENERAL" },
    { turkish: "hayır", ottoman: "خیر", category: "GENERAL" },
    { turkish: "lütfen", ottoman: "لطفا", category: "GENERAL" },
    { turkish: "tamam", ottoman: "تمام", category: "GENERAL" },
    { turkish: "güzel", ottoman: "گوزل", category: "GENERAL" },
    { turkish: "iyi", ottoman: "ایی", category: "GENERAL" },
    { turkish: "kötü", ottoman: "كوتو", category: "GENERAL" },
    { turkish: "büyük", ottoman: "بیوك", category: "GENERAL" },
    { turkish: "küçük", ottoman: "كوچوك", category: "GENERAL" },
    { turkish: "yeni", ottoman: "یڭی", category: "GENERAL" },
    { turkish: "eski", ottoman: "اسكی", category: "GENERAL" },
    { turkish: "var", ottoman: "وار", category: "GENERAL" },
    { turkish: "yok", ottoman: "یوق", category: "GENERAL" },
    { turkish: "gel", ottoman: "گل", category: "GENERAL" },
    { turkish: "git", ottoman: "گیت", category: "GENERAL" },
    { turkish: "kitap", ottoman: "كتاب", category: "GENERAL" },
    { turkish: "kalem", ottoman: "قلم", category: "GENERAL" },
    { turkish: "defter", ottoman: "دفتر", category: "GENERAL" },
    { turkish: "okul", ottoman: "مكتب", category: "GENERAL" },
    { turkish: "ev", ottoman: "او", category: "GENERAL" },
    { turkish: "iş", ottoman: "ایش", category: "GENERAL" },
    { turkish: "su", ottoman: "صو", category: "GENERAL" },
    { turkish: "ekmek", ottoman: "اكمك", category: "GENERAL" },
    { turkish: "çay", ottoman: "چای", category: "GENERAL" },
    { turkish: "kahve", ottoman: "قهوه", category: "GENERAL" },
    { turkish: "yemek", ottoman: "یمك", category: "GENERAL" },
    { turkish: "insan", ottoman: "انسان", category: "GENERAL" },
    { turkish: "adam", ottoman: "آدم", category: "GENERAL" },
    { turkish: "kadın", ottoman: "قادین", category: "GENERAL" },
    { turkish: "çocuk", ottoman: "چوجوق", category: "GENERAL" },
    { turkish: "dost", ottoman: "دوست", category: "GENERAL" },
    { turkish: "düşman", ottoman: "دشمن", category: "GENERAL" },
    { turkish: "aşk", ottoman: "عشق", category: "GENERAL" },
    { turkish: "sevgi", ottoman: "سوگی", category: "GENERAL" },
    { turkish: "kalp", ottoman: "قلب", category: "GENERAL" },
    { turkish: "gönül", ottoman: "گوڭل", category: "GENERAL" },
    { turkish: "ruh", ottoman: "روح", category: "GENERAL" },
    { turkish: "can", ottoman: "جان", category: "GENERAL" },
    { turkish: "hayat", ottoman: "حیات", category: "GENERAL" },
    { turkish: "ölüm", ottoman: "اولوم", category: "GENERAL" },
    { turkish: "dünya", ottoman: "دنیا", category: "GENERAL" },
    { turkish: "ahiret", ottoman: "آخرت", category: "GENERAL" },
    { turkish: "gün", ottoman: "گون", category: "GENERAL" },
    { turkish: "gece", ottoman: "گیجه", category: "GENERAL" },
    { turkish: "sabah", ottoman: "صباح", category: "GENERAL" },
    { turkish: "akşam", ottoman: "آقشام", category: "GENERAL" },
    { turkish: "yıl", ottoman: "ییل", category: "GENERAL" },
    { turkish: "ay", ottoman: "آی", category: "GENERAL" },
    { turkish: "hafta", ottoman: "هفته", category: "GENERAL" },
    { turkish: "saat", ottoman: "ساعت", category: "GENERAL" },
    { turkish: "dakika", ottoman: "دقیقه", category: "GENERAL" },

    // --- PRONOUNS (ZAMIR) ---
    { turkish: "ben", ottoman: "بن", category: "ZAMIR" },
    { turkish: "sen", ottoman: "سن", category: "ZAMIR" },
    { turkish: "o", ottoman: "او", category: "ZAMIR" },
    { turkish: "biz", ottoman: "بز", category: "ZAMIR" },
    { turkish: "siz", ottoman: "سز", category: "ZAMIR" },
    { turkish: "onlar", ottoman: "اونلر", category: "ZAMIR" },
    { turkish: "bu", ottoman: "بو", category: "ZAMIR" },
    { turkish: "şu", ottoman: "شو", category: "ZAMIR" },
    { turkish: "kim", ottoman: "كیم", category: "ZAMIR" },
    { turkish: "ne", ottoman: "نه", category: "ZAMIR" },
    { turkish: "nerede", ottoman: "نره ده", category: "ZAMIR" },
    { turkish: "nasıl", ottoman: "ناصل", category: "ZAMIR" },
    { turkish: "niçin", ottoman: "نیچون", category: "ZAMIR" },

    // --- VERBS (FIIL) ---
    { turkish: "yapmak", ottoman: "یاپمق", category: "FIIL" },
    { turkish: "etmek", ottoman: "ایتمك", category: "FIIL" },
    { turkish: "olmak", ottoman: "اولمق", category: "FIIL" },
    { turkish: "gelmek", ottoman: "گلمك", category: "FIIL" },
    { turkish: "gitmek", ottoman: "گیتمك", category: "FIIL" },
    { turkish: "görmek", ottoman: "گورمك", category: "FIIL" },
    { turkish: "bakmak", ottoman: "باقمق", category: "FIIL" },
    { turkish: "almak", ottoman: "آلمق", category: "FIIL" },
    { turkish: "vermek", ottoman: "ویرمك", category: "FIIL" },
    { turkish: "sevmek", ottoman: "سومك", category: "FIIL" },
    { turkish: "istemek", ottoman: "استمك", category: "FIIL" },
    { turkish: "bilmek", ottoman: "بیلمك", category: "FIIL" },
    { turkish: "anlamak", ottoman: "آڭلامق", category: "FIIL" },
    { turkish: "konuşmak", ottoman: "قونوشمق", category: "FIIL" },
    { turkish: "yazmak", ottoman: "یازمق", category: "FIIL" },
    { turkish: "okumak", ottoman: "اوقومق", category: "FIIL" },
    { turkish: "oturmak", ottoman: "اوتورمق", category: "FIIL" },
    { turkish: "kalkmak", ottoman: "قالقمق", category: "FIIL" },
    { turkish: "uyumak", ottoman: "اویومق", category: "FIIL" },
    { turkish: "uyanmak", ottoman: "اویاتمق", category: "FIIL" },
    { turkish: "yemek", ottoman: "یمك", category: "FIIL" },
    { turkish: "içmek", ottoman: "ایچمك", category: "FIIL" },
    { turkish: "gülmek", ottoman: "گولمك", category: "FIIL" },
    { turkish: "ağlamak", ottoman: "آغلامق", category: "FIIL" },
    { turkish: "çalışmak", ottoman: "چالیشمق", category: "FIIL" },
    { turkish: "düşünmek", ottoman: "دوشونمك", category: "FIIL" },
    { turkish: "söylemek", ottoman: "سویلمك", category: "FIIL" },
    { turkish: "duymak", ottoman: "دویمق", category: "FIIL" },
    { turkish: "başlamak", ottoman: "باشلامق", category: "FIIL" },
    { turkish: "bitmek", ottoman: "بیتمك", category: "FIIL" },

    // --- FAMILY (AILE) ---
    { turkish: "anne", ottoman: "آنه", category: "AILE" },
    { turkish: "baba", ottoman: "بابا", category: "AILE" },
    { turkish: "kardeş", ottoman: "قارداش", category: "AILE" },
    { turkish: "abla", ottoman: "آبلا", category: "AILE" },
    { turkish: "abi", ottoman: "آغابی", category: "AILE" },
    { turkish: "dede", ottoman: "دده", category: "AILE" },
    { turkish: "nine", ottoman: "ننه", category: "AILE" },
    { turkish: "teyze", ottoman: "تیزه", category: "AILE" },
    { turkish: "hala", ottoman: "حالا", category: "AILE" },
    { turkish: "amca", ottoman: "عموجه", category: "AILE" },
    { turkish: "dayı", ottoman: "دایی", category: "AILE" },
    { turkish: "oğul", ottoman: "اوغول", category: "AILE" },
    { turkish: "kız", ottoman: "قیز", category: "AILE" },
    { turkish: "eş", ottoman: "اش", category: "AILE" },
    { turkish: "aile", ottoman: "عائله", category: "AILE" },

    // --- GOVERNMENT / ADMIN (IDARI) ---
    { turkish: "devlet", ottoman: "دولت", category: "IDARI" },
    { turkish: "hükümet", ottoman: "حكومت", category: "IDARI" },
    { turkish: "millet", ottoman: "ملت", category: "IDARI" },
    { turkish: "vatan", ottoman: "وطن", category: "IDARI" },
    { turkish: "kanun", ottoman: "قانون", category: "IDARI" },
    { turkish: "adalet", ottoman: "عدالت", category: "IDARI" },
    { turkish: "hakim", ottoman: "حاكم", category: "IDARI" },
    { turkish: "mahkeme", ottoman: "محكمه", category: "IDARI" },
    { turkish: "asker", ottoman: "عسكر", category: "IDARI" },
    { turkish: "ordu", ottoman: "اردو", category: "IDARI" },
    { turkish: "savaş", ottoman: "صاواش", category: "IDARI" },
    { turkish: "barış", ottoman: "باریش", category: "IDARI" },
    { turkish: "meclis", ottoman: "مجلس", category: "IDARI" },
    { turkish: "bakan", ottoman: "ناظر", category: "IDARI" },
    { turkish: "başkan", ottoman: "رئیس", category: "IDARI" },
    { turkish: "müdür", ottoman: "مدیر", category: "IDARI" },
    { turkish: "memur", ottoman: "مأمور", category: "IDARI" },
    { turkish: "evrak", ottoman: "اوراق", category: "IDARI" },
    { turkish: "imza", ottoman: "امضا", category: "IDARI" },
    { turkish: "mühür", ottoman: "مهر", category: "IDARI" },

    // --- RELIGION (DINI) ---
    { turkish: "allah", ottoman: "الله", category: "DINI" },
    { turkish: "peygamber", ottoman: "پیغمبر", category: "DINI" },
    { turkish: "kitap", ottoman: "كتاب", category: "DINI" },
    { turkish: "kuran", ottoman: "قرآن", category: "DINI" },
    { turkish: "cami", ottoman: "جامع", category: "DINI" },
    { turkish: "namaz", ottoman: "نماز", category: "DINI" },
    { turkish: "oruç", ottoman: "اوروج", category: "DINI" },
    { turkish: "zekat", ottoman: "زكات", category: "DINI" },
    { turkish: "hac", ottoman: "حج", category: "DINI" },
    { turkish: "cennet", ottoman: "جنت", category: "DINI" },
    { turkish: "cehennem", ottoman: "جهنم", category: "DINI" },
    { turkish: "melek", ottoman: "ملك", category: "DINI" },
    { turkish: "şeytan", ottoman: "شیطان", category: "DINI" },
    { turkish: "dua", ottoman: "دعا", category: "DINI" },
    { turkish: "iman", ottoman: "ایمان", category: "DINI" },
    { turkish: "ibadet", ottoman: "عبادت", category: "DINI" },
    { turkish: "sevap", ottoman: "ثواب", category: "DINI" },
    { turkish: "günah", ottoman: "گناه", category: "DINI" },
    { turkish: "helal", ottoman: "حلال", category: "DINI" },
    { turkish: "haram", ottoman: "حرام", category: "DINI" },

    // --- ABSTRACT / ACADEMIC (SOYUT) ---
    { turkish: "ilim", ottoman: "علم", category: "SOYUT" },
    { turkish: "irfan", ottoman: "عرفان", category: "SOYUT" },
    { turkish: "hikmet", ottoman: "حكمت", category: "SOYUT" },
    { turkish: "akıl", ottoman: "عقل", category: "SOYUT" },
    { turkish: "fikir", ottoman: "فكر", category: "SOYUT" },
    { turkish: "düşünce", ottoman: "دوشونجه", category: "SOYUT" },
    { turkish: "sanat", ottoman: "صنعت", category: "SOYUT" },
    { turkish: "edebiyat", ottoman: "ادبیات", category: "SOYUT" },
    { turkish: "tarih", ottoman: "تاریخ", category: "SOYUT" },
    { turkish: "coğrafya", ottoman: "جغرافیا", category: "SOYUT" },
    { turkish: "felsefe", ottoman: "فلسفه", category: "SOYUT" },
    { turkish: "mantık", ottoman: "منطق", category: "SOYUT" },
    { turkish: "matematik", ottoman: "ریاضیه", category: "SOYUT" },
    { turkish: "fizik", ottoman: "حكمت طبیعیه", category: "SOYUT" },
    { turkish: "kimya", ottoman: "كیمیا", category: "SOYUT" },
    { turkish: "biyoloji", ottoman: "حیاتیات", category: "SOYUT" },
    { turkish: "ruh", ottoman: "روح", category: "SOYUT" },
    { turkish: "nefs", ottoman: "نفس", category: "SOYUT" },
    { turkish: "kalp", ottoman: "قلب", category: "SOYUT" },
    { turkish: "vicdan", ottoman: "وجدان", category: "SOYUT" },

    // --- ADJECTIVES (SIFAT) ---
    { turkish: "güzel", ottoman: "گوزل", category: "SIFAT" },
    { turkish: "çirkin", ottoman: "چیركین", category: "SIFAT" },
    { turkish: "iyi", ottoman: "ایی", category: "SIFAT" },
    { turkish: "kötü", ottoman: "كوتو", category: "SIFAT" },
    { turkish: "doğru", ottoman: "دوغرو", category: "SIFAT" },
    { turkish: "yanlış", ottoman: "یاڭلیش", category: "SIFAT" },
    { turkish: "uzun", ottoman: "اوزون", category: "SIFAT" },
    { turkish: "kısa", ottoman: "قیصه", category: "SIFAT" },
    { turkish: "büyük", ottoman: "بیوك", category: "SIFAT" },
    { turkish: "küçük", ottoman: "كوچوك", category: "SIFAT" },
    { turkish: "geniş", ottoman: "گنیش", category: "SIFAT" },
    { turkish: "dar", ottoman: "دار", category: "SIFAT" },
    { turkish: "yüksek", ottoman: "یوكسك", category: "SIFAT" },
    { turkish: "alçak", ottoman: "آلچاق", category: "SIFAT" },
    { turkish: "sıcak", ottoman: "صیجاق", category: "SIFAT" },
    { turkish: "soğuk", ottoman: "صوغوق", category: "SIFAT" },
    { turkish: "zengin", ottoman: "زنگین", category: "SIFAT" },
    { turkish: "fakir", ottoman: "فقیر", category: "SIFAT" },
    { turkish: "mutlu", ottoman: "موتلو", category: "SIFAT" },
    { turkish: "üzgün", ottoman: "اوزگون", category: "SIFAT" },
    { turkish: "akıllı", ottoman: "عقللی", category: "SIFAT" },
    { turkish: "deli", ottoman: "دلی", category: "SIFAT" },
    { turkish: "güçlü", ottoman: "گوچلو", category: "SIFAT" },
    { turkish: "zayıf", ottoman: "ضعیف", category: "SIFAT" },
    { turkish: "hızlı", ottoman: "هیزلی", category: "SIFAT" },
    { turkish: "yavaş", ottoman: "یاواش", category: "SIFAT" },
    { turkish: "kolay", ottoman: "قولای", category: "SIFAT" },
    { turkish: "zor", ottoman: "زور", category: "SIFAT" },
    { turkish: "açık", ottoman: "آچیق", category: "SIFAT" },
    { turkish: "kapalı", ottoman: "قاپالی", category: "SIFAT" },
    { turkish: "temiz", ottoman: "تمیز", category: "SIFAT" },
    { turkish: "kirli", ottoman: "كیرلی", category: "SIFAT" },
    { turkish: "yeni", ottoman: "یڭی", category: "SIFAT" },
    { turkish: "eski", ottoman: "اسكی", category: "SIFAT" },
    { turkish: "genç", ottoman: "گنچ", category: "SIFAT" },
    { turkish: "ihtiyar", ottoman: "اختیار", category: "SIFAT" },
    { turkish: "sağ", ottoman: "صاغ", category: "SIFAT" },
    { turkish: "sol", ottoman: "صول", category: "SIFAT" },
    { turkish: "boş", ottoman: "بوش", category: "SIFAT" },
    { turkish: "dolu", ottoman: "دولو", category: "SIFAT" },

    // --- TIME (ZAMAN) ---
    { turkish: "zaman", ottoman: "زمان", category: "ZAMAN" },
    { turkish: "vakit", ottoman: "وقت", category: "ZAMAN" },
    { turkish: "an", ottoman: "آن", category: "ZAMAN" },
    { turkish: "saniye", ottoman: "ثانیه", category: "ZAMAN" },
    { turkish: "dakika", ottoman: "دقیقه", category: "ZAMAN" },
    { turkish: "saat", ottoman: "ساعت", category: "ZAMAN" },
    { turkish: "gün", ottoman: "گون", category: "ZAMAN" },
    { turkish: "hafta", ottoman: "هفته", category: "ZAMAN" },
    { turkish: "ay", ottoman: "آی", category: "ZAMAN" },
    { turkish: "yıl", ottoman: "ییل", category: "ZAMAN" },
    { turkish: "sene", ottoman: "سنه", category: "ZAMAN" },
    { turkish: "yüzyıl", ottoman: "یوز ییل", category: "ZAMAN" },
    { turkish: "asır", ottoman: "عصر", category: "ZAMAN" },
    { turkish: "dün", ottoman: "دون", category: "ZAMAN" },
    { turkish: "bugün", ottoman: "بوگون", category: "ZAMAN" },
    { turkish: "yarın", ottoman: "یارین", category: "ZAMAN" },
    { turkish: "sabah", ottoman: "صباح", category: "ZAMAN" },
    { turkish: "öğle", ottoman: "اوگله", category: "ZAMAN" },
    { turkish: "ikindi", ottoman: "ایكندی", category: "ZAMAN" },
    { turkish: "akşam", ottoman: "آقشام", category: "ZAMAN" },
    { turkish: "yatsı", ottoman: "یاتصو", category: "ZAMAN" },
    { turkish: "gece", ottoman: "گیجه", category: "ZAMAN" },
    { turkish: "evvel", ottoman: "اول", category: "ZAMAN" },
    { turkish: "sonra", ottoman: "صوڭره", category: "ZAMAN" },
    { turkish: "şimdi", ottoman: "شیمدی", category: "ZAMAN" },
    { turkish: "derhal", ottoman: "درحال", category: "ZAMAN" },
    { turkish: "daima", ottoman: "دائما", category: "ZAMAN" },
    { turkish: "asla", ottoman: "اصلا", category: "ZAMAN" },
    { turkish: "bazen", ottoman: "بعضا", category: "ZAMAN" },
    { turkish: "sık sık", ottoman: "صیق صیق", category: "ZAMAN" },

    // --- NATURE (DOGA) ---
    { turkish: "doğa", ottoman: "طبیعت", category: "GENERAL" },
    { turkish: "tabiat", ottoman: "طبیعت", category: "GENERAL" },
    { turkish: "yer", ottoman: "یر", category: "GENERAL" },
    { turkish: "gök", ottoman: "كوك", category: "GENERAL" },
    { turkish: "güneş", ottoman: "گونش", category: "GENERAL" },
    { turkish: "ay", ottoman: "آی", category: "GENERAL" },
    { turkish: "yıldız", ottoman: "ییلدیز", category: "GENERAL" },
    { turkish: "bulut", ottoman: "بولوت", category: "GENERAL" },
    { turkish: "yağmur", ottoman: "یاغمور", category: "GENERAL" },
    { turkish: "kar", ottoman: "قار", category: "GENERAL" },
    { turkish: "rüzgar", ottoman: "روزگار", category: "GENERAL" },
    { turkish: "fırtına", ottoman: "فرطینه", category: "GENERAL" },
    { turkish: "deniz", ottoman: "دڭز", category: "GENERAL" },
    { turkish: "göl", ottoman: "گول", category: "GENERAL" },
    { turkish: "nehir", ottoman: "نهر", category: "GENERAL" },
    { turkish: "ırmak", ottoman: "ایرماق", category: "GENERAL" },
    { turkish: "dağ", ottoman: "داغ", category: "GENERAL" },
    { turkish: "tepe", ottoman: "تپه", category: "GENERAL" },
    { turkish: "ova", ottoman: "اوه", category: "GENERAL" },
    { turkish: "orman", ottoman: "اورمان", category: "GENERAL" },
    { turkish: "ağaç", ottoman: "آغاج", category: "GENERAL" },
    { turkish: "çiçek", ottoman: "چیچك", category: "GENERAL" },
    { turkish: "yaprak", ottoman: "یاپراق", category: "GENERAL" },
    { turkish: "toprak", ottoman: "طوپراق", category: "GENERAL" },
    { turkish: "taş", ottoman: "طاش", category: "GENERAL" },
    { turkish: "ateş", ottoman: "آتش", category: "GENERAL" },
    { turkish: "hava", ottoman: "هوا", category: "GENERAL" },
    { turkish: "su", ottoman: "صو", category: "GENERAL" },

    // --- ANIMALS (HAYVANLAR) ---
    { turkish: "hayvan", ottoman: "حیوان", category: "GENERAL" },
    { turkish: "at", ottoman: "آت", category: "GENERAL" },
    { turkish: "eşek", ottoman: "اشك", category: "GENERAL" },
    { turkish: "katır", ottoman: "قاطر", category: "GENERAL" },
    { turkish: "deve", ottoman: "دوه", category: "GENERAL" },
    { turkish: "koyun", ottoman: "قویون", category: "GENERAL" },
    { turkish: "keçi", ottoman: "كچی", category: "GENERAL" },
    { turkish: "inek", ottoman: "اینك", category: "GENERAL" },
    { turkish: "öküz", ottoman: "اوكوز", category: "GENERAL" },
    { turkish: "manda", ottoman: "مانده", category: "GENERAL" },
    { turkish: "köpek", ottoman: "كوپك", category: "GENERAL" },
    { turkish: "kedi", ottoman: "كدی", category: "GENERAL" },
    { turkish: "aslan", ottoman: "آرسلان", category: "GENERAL" },
    { turkish: "kaplan", ottoman: "قاپلان", category: "GENERAL" },
    { turkish: "kurt", ottoman: "قورت", category: "GENERAL" },
    { turkish: "tilki", ottoman: "tilki", category: "GENERAL" },
    { turkish: "ayı", ottoman: "آیی", category: "GENERAL" },
    { turkish: "kuş", ottoman: "قوش", category: "GENERAL" },
    { turkish: "kartal", ottoman: "قارطال", category: "GENERAL" },
    { turkish: "şahin", ottoman: "شاهین", category: "GENERAL" },
    { turkish: "güvercin", ottoman: "گوگرچین", category: "GENERAL" },
    { turkish: "tavuk", ottoman: "طاووق", category: "GENERAL" },
    { turkish: "horoz", ottoman: "خروس", category: "GENERAL" },
    { turkish: "balık", ottoman: "بالیق", category: "GENERAL" },
    { turkish: "yılan", ottoman: "ییلان", category: "GENERAL" },
    { turkish: "böcek", ottoman: "بوجك", category: "GENERAL" },
    { turkish: "arı", ottoman: "آری", category: "GENERAL" },
    { turkish: "karınca", ottoman: "قارنجه", category: "GENERAL" },
    { turkish: "sinek", ottoman: "سیڭك", category: "GENERAL" },

    // --- BODY (VUCUT) ---
    { turkish: "vücut", ottoman: "وجود", category: "GENERAL" },
    { turkish: "baş", ottoman: "باش", category: "GENERAL" },
    { turkish: "kafa", ottoman: "قفا", category: "GENERAL" },
    { turkish: "saç", ottoman: "صاچ", category: "GENERAL" },
    { turkish: "yüz", ottoman: "یوز", category: "GENERAL" },
    { turkish: "alın", ottoman: "آلڭ", category: "GENERAL" },
    { turkish: "göz", ottoman: "گوز", category: "GENERAL" },
    { turkish: "kaş", ottoman: "قاش", category: "GENERAL" },
    { turkish: "kirpik", ottoman: "kirpik", category: "GENERAL" },
    { turkish: "burun", ottoman: "بورون", category: "GENERAL" },
    { turkish: "kulak", ottoman: "قولاق", category: "GENERAL" },
    { turkish: "ağız", ottoman: "آغز", category: "GENERAL" },
    { turkish: "dudak", ottoman: "دوداق", category: "GENERAL" },
    { turkish: "diş", ottoman: "دیش", category: "GENERAL" },
    { turkish: "dil", ottoman: "دل", category: "GENERAL" },
    { turkish: "boğaz", ottoman: "بوغاز", category: "GENERAL" },
    { turkish: "boyun", ottoman: "بویون", category: "GENERAL" },
    { turkish: "omuz", ottoman: "اوموز", category: "GENERAL" },
    { turkish: "kol", ottoman: "قول", category: "GENERAL" },
    { turkish: "el", ottoman: "ال", category: "GENERAL" },
    { turkish: "parmak", ottoman: "پرمق", category: "GENERAL" },
    { turkish: "tırnak", ottoman: "طرناق", category: "GENERAL" },
    { turkish: "göğüs", ottoman: "گوگس", category: "GENERAL" },
    { turkish: "sırt", ottoman: "صیرت", category: "GENERAL" },
    { turkish: "karın", ottoman: "قارن", category: "GENERAL" },
    { turkish: "bel", ottoman: "بل", category: "GENERAL" },
    { turkish: "bacak", ottoman: "باجاق", category: "GENERAL" },
    { turkish: "diz", ottoman: "دیز", category: "GENERAL" },
    { turkish: "ayak", ottoman: "آیاق", category: "GENERAL" },
    { turkish: "deri", ottoman: "دری", category: "GENERAL" },
    { turkish: "kemik", ottoman: "كمیك", category: "GENERAL" },
    { turkish: "kan", ottoman: "قان", category: "GENERAL" },

    // --- COLORS (RENKLER) ---
    { turkish: "renk", ottoman: "رنگ", category: "SIFAT" },
    { turkish: "beyaz", ottoman: "بیاض", category: "SIFAT" },
    { turkish: "ak", ottoman: "آق", category: "SIFAT" },
    { turkish: "siyah", ottoman: "سیاه", category: "SIFAT" },
    { turkish: "kara", ottoman: "قره", category: "SIFAT" },
    { turkish: "kırmızı", ottoman: "قیرمزی", category: "SIFAT" },
    { turkish: "al", ottoman: "آل", category: "SIFAT" },
    { turkish: "yeşil", ottoman: "یشیل", category: "SIFAT" },
    { turkish: "mavi", ottoman: "ماوی", category: "SIFAT" },
    { turkish: "gök", ottoman: "كوك", category: "SIFAT" },
    { turkish: "sarı", ottoman: "صاری", category: "SIFAT" },
    { turkish: "turuncu", ottoman: "ترنجی", category: "SIFAT" },
    { turkish: "mor", ottoman: "مور", category: "SIFAT" },
    { turkish: "pembe", ottoman: "پنبه", category: "SIFAT" },
    { turkish: "kahverengi", ottoman: "قهوه رنگی", category: "SIFAT" },
    { turkish: "gri", ottoman: "گری", category: "SIFAT" },
    { turkish: "lacivert", ottoman: "لاجوردی", category: "SIFAT" },

    // --- NUMBERS (SAYILAR) ---
    { turkish: "bir", ottoman: "بر", category: "GENERAL" },
    { turkish: "iki", ottoman: "ایكی", category: "GENERAL" },
    { turkish: "üç", ottoman: "اوچ", category: "GENERAL" },
    { turkish: "dört", ottoman: "درت", category: "GENERAL" },
    { turkish: "beş", ottoman: "بش", category: "GENERAL" },
    { turkish: "altı", ottoman: "آلتی", category: "GENERAL" },
    { turkish: "yedi", ottoman: "یدی", category: "GENERAL" },
    { turkish: "sekiz", ottoman: "سكیز", category: "GENERAL" },
    { turkish: "dokuz", ottoman: "دوقوز", category: "GENERAL" },
    { turkish: "on", ottoman: "اون", category: "GENERAL" },
    { turkish: "yirmi", ottoman: "یگرمی", category: "GENERAL" },
    { turkish: "otuz", ottoman: "اوتوز", category: "GENERAL" },
    { turkish: "kırk", ottoman: "قیرق", category: "GENERAL" },
    { turkish: "elli", ottoman: "اللی", category: "GENERAL" },
    { turkish: "altmış", ottoman: "آلتمیش", category: "GENERAL" },
    { turkish: "yetmiş", ottoman: "یتمیش", category: "GENERAL" },
    { turkish: "seksen", ottoman: "سكسن", category: "GENERAL" },
    { turkish: "doksan", ottoman: "دوقسان", category: "GENERAL" },
    { turkish: "yüz", ottoman: "یوز", category: "GENERAL" },
    { turkish: "bin", ottoman: "بیڭ", category: "GENERAL" },
    { turkish: "milyon", ottoman: "میلیون", category: "GENERAL" },
    { turkish: "sıfır", ottoman: "صفر", category: "GENERAL" },
    { turkish: "yarım", ottoman: "یاریم", category: "GENERAL" },
    { turkish: "çeyrek", ottoman: "چیرك", category: "GENERAL" },

    // --- DIRECTIONS (YONLER) ---
    { turkish: "yön", ottoman: "یون", category: "GENERAL" },
    { turkish: "kuzey", ottoman: "شمال", category: "GENERAL" },
    { turkish: "güney", ottoman: "جنوب", category: "GENERAL" },
    { turkish: "doğu", ottoman: "شرق", category: "GENERAL" },
    { turkish: "batı", ottoman: "غرب", category: "GENERAL" },
    { turkish: "sağ", ottoman: "صاغ", category: "GENERAL" },
    { turkish: "sol", ottoman: "صول", category: "GENERAL" },
    { turkish: "ön", ottoman: "اوڭ", category: "GENERAL" },
    { turkish: "arka", ottoman: "آرقه", category: "GENERAL" },
    { turkish: "yukarı", ottoman: "یوقاری", category: "GENERAL" },
    { turkish: "aşağı", ottoman: "آشاغی", category: "GENERAL" },
    { turkish: "iç", ottoman: "ایچ", category: "GENERAL" },
    { turkish: "dış", ottoman: "دیش", category: "GENERAL" },
    { turkish: "orta", ottoman: "اورطه", category: "GENERAL" },
    { turkish: "yan", ottoman: "یان", category: "GENERAL" },
    { turkish: "karşı", ottoman: "قارشی", category: "GENERAL" }
];

db.serialize(() => {
    console.log('Seeding database...');

    // Use INSERT OR IGNORE to prevent duplicates
    const stmt = db.prepare("INSERT OR IGNORE INTO dictionary (turkish, ottoman, category) VALUES (?, ?, ?)");

    GLOBAL_DICTIONARY.forEach(word => {
        stmt.run(word.turkish, word.ottoman, word.category);
    });

    stmt.finalize(() => {
        console.log(`Seeded ${GLOBAL_DICTIONARY.length} words into the dictionary.`);
        db.close();
    });
});
